[package]
name = "map"
version = "0.1.0"
authors = ["Mitch S. <mitch+map@applicative.us>"]

[dependencies]
clap = "~2.32.0"
regex = "1"
log = "0.4.4"
log4rs = "0.8.0"
error-chain = "0.12.0"

[dev-dependencies]
rand = "0.5.5"